par/frontend/urls.py
from django.urls import path
from .views import *

app_name = "frontend"
urlpatterns = [
    path('', index, name='index'),
    path('about-us/', aboutus, name='aboutus'),
    path('management/', management, name='management'),
    path('our-business/', our_business, name='our_business'),
    
    path('investor/', investor, name='investor'),
    path('contact-us/', contactus, name='contactus'),
    path('portal/', portal, name='portal'),

    path('news/', news, name='news'),
    path("news/<str:slug>", news_detail, name="news_detail"),
    path("article/<str:slug>", article_detail, name="article_detail"),

    path('tender/', tender, name='tender'),
    path("tender/<str:slug>", tender_detail, name="tender_detail"),
    path('career/', career, name='career'),
    path("career/<str:slug>", career_detail, name="career_detail"),

    path('gallery/', gallery, name='gallery'),
    path("gallery/<str:slug>", gallery_detail, name="gallery_detail"),
    path("tjsl", tjsl, name="tjsl"),
    path("search", search, name="search"),
    path('api-subscribe/', subscribe, name='subscribe'),
]

par/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "PAR"
admin.site.site_title = "PAR Admin Portal"
admin.site.index_title = "Welcome to PAR Admin Portal"

from django.contrib.auth.models import Group
from django_summernote.models import Attachment

from django.conf.urls.i18n import i18n_patterns

admin.site.unregister(Group)
admin.site.unregister(Attachment)

urlpatterns = i18n_patterns (
    path('', include('par.frontend.urls', namespace='frontend')),
    path('par-admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')), # using include('django_summernote.urls')
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# di server saat settings debug true
if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)

par/apps/content/models.py
from par.core.utils import FilenameGenerator, custom_slugify
from django.db import models
from taggit.managers import TaggableManager


class Portal(models.Model):
    class Meta:
        verbose_name = 'Portal'
        verbose_name_plural = 'Portal'

    img =  models.ImageField(upload_to=FilenameGenerator(
        prefix='banner'))

    id_big_text = models.TextField(null=True)
    en_big_text = models.TextField(null=True)
    
    id_small_text = models.TextField(null=True)
    en_small_text = models.TextField(null=True)

    link = models.CharField(max_length=254, null=True)
    is_active = models.BooleanField(default=True, null=True)

    def __str__(self):
        return f"{self.id_big_text}"


class Menu(models.Model):
    class Meta:
        verbose_name = 'Top Menu'
        verbose_name_plural = 'Top Menu'
    id_title = models.CharField(max_length=254, null=True)
    en_title = models.CharField(max_length=254, null=True)
    order = models.PositiveSmallIntegerField(default=1)
   
    def __str__(self):
        return f"{self.id}"


class Banner(models.Model):
    class Meta:
        verbose_name = 'Home Banner'
        verbose_name_plural = 'Home Banner'

    img =  models.ImageField(upload_to=FilenameGenerator(
        prefix='banner'))

    id_big_text = models.TextField(null=True)
    en_big_text = models.TextField(null=True)
    
    id_small_text = models.TextField(null=True)
    en_small_text = models.TextField(null=True)
    
    is_active = models.BooleanField(default=True, null=True)

    def __str__(self):
        return f"{self.id_big_text}"


class OurBusiness(models.Model):
    class Meta:
        verbose_name = 'Our Business'
        verbose_name_plural = 'Our Business'
    img =  models.ImageField("image", upload_to=FilenameGenerator(
        prefix='banner'))
    logo =  models.ImageField("logo", upload_to=FilenameGenerator(
            prefix='logo'))
    
    id_title = models.CharField(max_length=254)
    id_short_desc = models.CharField(max_length=254)
    id_long_desc = models.TextField()

    en_title = models.CharField(max_length=254)
    en_short_desc = models.CharField(max_length=254)
    en_long_desc = models.TextField()

    order = models.PositiveIntegerField(default=0)

    is_active = models.BooleanField("Published", default=True)
    slug = models.CharField(unique=True, max_length=254, blank=True)
    
    def __str__(self):
        return f"{self.id_title}"

    # def preview(self):
    #     return mark_safe('<a href="/news/%s" target="_blank"/> preview </a>' % self.slug)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.id_title)
        super(OurBusiness, self).save()


class NewsTag(models.Model):
    class Meta:
        verbose_name = 'News & Article Category'
        verbose_name_plural = 'News & Article Category'
    id_title = models.CharField(max_length=254, null=True)
    en_title = models.CharField(max_length=254, null=True)
    color = models.CharField(max_length=10, null=True)
    bg_color = models.CharField(max_length=10, null=True)
    
    def __str__(self):
        return self.id_title


# registered
class News(models.Model):
    class Meta:
        verbose_name = 'News & Article'
        verbose_name_plural = 'News & Article'
    img =  models.ImageField("image", upload_to=FilenameGenerator(
        prefix='banner'))
    
    id_title = models.CharField(max_length=254)
    id_short_desc = models.CharField(max_length=254)
    id_long_desc = models.TextField()

    en_title = models.CharField(max_length=254)
    en_short_desc = models.CharField(max_length=254)
    en_long_desc = models.TextField()

    date = models.DateField(blank=True)
    is_active = models.BooleanField("Published", default=True)
    categories = models.ManyToManyField(NewsTag)
    slug = models.CharField(unique=True, max_length=254, blank=True)
    TYPE = (
        ('artikel', 'artikel'),
        ('news', 'news'),
    )
    type = models.CharField(max_length=254, choices=TYPE, null=True)
    
    def __str__(self):
        return f"{self.id_title}"

    # def preview(self):
    #     return mark_safe('<a href="/news/%s" target="_blank"/> preview </a>' % self.slug)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.id_title)
        super(News, self).save()


# registered
class YearlyReport(models.Model):
    class Meta:
        verbose_name = 'About Us - Yearly Report'
        verbose_name_plural = 'About Us - Yearly Report'
    img =  models.ImageField("image", upload_to=FilenameGenerator(
        prefix='banner'))
    
    id_title = models.CharField(max_length=254)
    en_title = models.CharField(max_length=254)

    is_active = models.BooleanField("Published", default=True)
    slug = models.CharField(unique=True, max_length=254, blank=True)
    file =  models.FileField("file", upload_to=FilenameGenerator(
        prefix='file'), null=True)
    
    def __str__(self):
        return f"{self.id} {self.id_title}"

    # def preview(self):
    #     return mark_safe('<a href="/news/%s" target="_blank"/> preview </a>' % self.slug)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.id_title)
        super(YearlyReport, self).save()


#registered
class History(models.Model):
    class Meta:
        verbose_name = 'About Us - Milestone'
        verbose_name_plural = 'About Us - Milestone'

    id_title = models.CharField(max_length=254, null=True)
    en_title = models.CharField(max_length=254, null=True)
    
    id_long_desc = models.TextField()
    en_long_desc = models.TextField()
    year = models.IntegerField()
    is_active = models.BooleanField("Published", default=True)
    
    def __str__(self):
        return f"{self.id} {self.id_title}"

    # def preview(self):
    #     return mark_safe('<a href="/news/%s" target="_blank"/> preview </a>' % self.slug)

    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         self.slug = custom_slugify(self.title)
    #     super(History, self).save()
    

# registered
class DirectorProfile(models.Model):
    class Meta:
        verbose_name = 'AboutUs - Profile'
        verbose_name_plural = 'AboutUs - Profile'
    name = models.CharField(max_length=254)
    id_position = models.CharField(max_length=254, null=True)
    en_position = models.CharField(max_length=254, null=True)
    is_active = models.BooleanField("Published", default=True)
    id_long_desc = models.TextField()
    en_long_desc = models.TextField()
    img =  models.ImageField("image", upload_to=FilenameGenerator(
        prefix='profile_direktur'), null=True)
    TYPE = (
        ('direksi', 'direksi'),
        ('komisaris', 'komisaris'),
    )
    type = models.CharField(max_length=254, choices=TYPE)
    
    def __str__(self):
        return self.name

    # def preview(self):
    #     return mark_safe('<a href="/news/%s" target="_blank"/> preview </a>' % self.slug)


# registered
class Award(models.Model):
    id_title = models.CharField(null=True ,max_length=254)
    en_title = models.CharField(null=True, max_length=254)
    class Meta:
        verbose_name = 'About Us - Award'
        verbose_name_plural = 'About Us - Award'
    img =  models.ImageField("image", upload_to=FilenameGenerator(
        prefix='banner'))
    id_description = models.TextField()
    en_description = models.TextField()
    is_active = models.BooleanField("Published", default=True)
    month_year = models.CharField(max_length=254, null=True)
    
    def __str__(self):
        return f"{self.id} {self.id_title}"

    # def preview(self):
    #     return mark_safe('<a href="/news/%s" target="_blank"/> preview </a>' % self.slug)

    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         self.slug = custom_slugify(self.title)
    #     super(OurBusiness, self).save()


# registered
class Certicate(models.Model):
    id_title = models.CharField(null=True ,max_length=254)
    en_title = models.CharField(null=True, max_length=254)
    class Meta:
        verbose_name = 'About Us - Certicate'
        verbose_name_plural = 'About Us - Certicate'
    img =  models.ImageField("image", upload_to=FilenameGenerator(
        prefix='banner'))
    id_description = models.TextField()
    en_description = models.TextField()
    year = models.CharField(max_length=254)
    is_active = models.BooleanField("Published", default=True)
    slug = models.CharField(unique=True, max_length=254, blank=True)
    
    def __str__(self):
        return f"{self.id} {self.id_title}"

    # def preview(self):
    #     return mark_safe('<a href="/news/%s" target="_blank"/> preview </a>' % self.slug)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.id_description)
        super(Certicate, self).save()


# registered
class Album(models.Model):
    class Meta:
        verbose_name = 'Gallery & TJSL'
        verbose_name_plural = 'Gallery & TJSL'
    img =  models.ImageField("image", upload_to=FilenameGenerator(
        prefix='banner'))
    id_title = models.TextField(null=True)
    en_title = models.TextField(null=True)
    date = models.DateField()
    is_active = models.BooleanField("Published", default=True)
    slug = models.CharField(unique=True, max_length=254, blank=True)
    total_photo = models.IntegerField(default=0, null=True)
    total_video = models.IntegerField(default=0, null=True)

    def __str__(self):
        return self.id_title

    # def preview(self):
    #     return mark_safe('<a href="/news/%s" target="_blank"/> preview </a>' % self.slug)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.id_title)
        super(Album, self).save()


class Gallery(models.Model):
    class Meta:
        verbose_name = 'Gallery'
        verbose_name_plural = 'Gallery'

par/apps/settings copy/models.py
from par.core.utils import FilenameGenerator
from django.db import models


class Settings(models.Model):
    TYPE = (
        ('seo_description', 'SEO Description'),
        ('seo_title', 'SEO Title'),
        ('seo_keywords', 'SEO Keywords'),
        ('seo_image', 'SEO Image'),
        ('seo_fb_id', 'SEO FbID'),
    )
    name = models.CharField(max_length=254, choices=TYPE, unique=True)
    text_value = models.TextField(blank=True, null=True)
    img_value =  models.ImageField(upload_to=FilenameGenerator(
        prefix='settings'), blank=True, null=True)

    def __str__(self):
        return self.name

par/apps/user/models.py
from django.contrib.auth.models import (
    AbstractBaseUser, PermissionsMixin, UserManager
)
from django.db import models
from django.utils import timezone


class CustomUserManager(UserManager):
    def create_user(self, username, password, **extra_fields):
        now = timezone.now()
        user = self.model(
            username=username,
            is_active=True, is_superuser=False,
            last_login=now, **extra_fields)

        if password:
            user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, username, password, **extra_fields):
        user = self.create_user(username, password, **extra_fields)
        user.is_staff = True
        user.is_active = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=50, unique=True, db_index=True)
    name = models.CharField(max_length=50, null=True)
    is_active = models.BooleanField('active', default=True)
    is_staff = models.BooleanField('Status Staff', default=False)
    mobile_number = models.CharField(max_length=30, default='', blank=True)
    dealer_name = models.CharField(max_length=100, blank=True, null=True)
    dealer_address = models.CharField(max_length=100, blank=True, null=True)
    USERNAME_FIELD = 'username'
    objects = CustomUserManager()

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

    def __str__(self):
        return '%s - %s' % (self.username, self.name)

    def __unicode__(self):
        return '%s - %s' % (self.username, self.name)

    def serialize(self):
        return  {
            "username" : self.username,
            "name" : self.name,
            "mobile_number" : self.mobile_number,
            "dealer_name" : self.dealer_name,
            "dealer_address" : self.dealer_address,
        }

    # def save(self, *args, **kwargs):
    #     exist_id = self.id
    #     super(User, self).save(*args, **kwargs)

    #     self.kabupaten = Kabupaten.objects.first()
    #     self.provinsi = Provinsi.objects.first()
        
    #     if not exist_id:
    #         self.order = get_next_value("order_user")
    #         PrintCard.objects.create(user=self, order=self.order)
    #         self.save()

par/frontend/forms.py
from django import forms
from par.apps.content.models import Contact, EmailSubscribe


class ContactForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()
    phone_number = forms.CharField()
    message = forms.CharField()
    def save(self):
        data = self.cleaned_data
        contact, _ = Contact.objects.update_or_create(
            phone_number = data['phone_number'],
            email = data['email'],
            defaults = {
                "email" : data['email'],
                "phone_number" : data['phone_number'], 
                "first_name" : data['first_name'], 
                "last_name" : data['last_name'], 
                "message" : data['message'], 
            }
        )
        return contact


class RedeemForm(forms.Form):
    email = forms.CharField()
    def save(self):
        data = self.cleaned_data
        subs, _ = EmailSubscribe.objects.update_or_create(
            email = data['email'],
        )
        return subs

par/apps/content/views.py
from django.shortcuts import render

# Create your views here.

par/apps/settings copy/views.py
from django.shortcuts import render

# Create your views here.

par/apps/user/views.py
from django.shortcuts import render

# Create your views here.

par/templates/frontend/base.html
{% load static %} 
{% load humanize %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="Yusmin" />
    <meta name="generator" content="Hugo 0.88.1" />
    <title>{{title}}</title>
    {% include "./meta.html" %}
    <link
      rel="canonical"
      href="https://getbootstrap.com/docs/5.1/examples/navbar-fixed/"
    />
    <link href="{% static 'css/bootstrap.min.css'  %}" rel="stylesheet" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link href="{% static 'css/mystyle.css'  %}" rel="stylesheet" />
    <script type="text/javascript">
      window.CSRF_TOKEN = "{{ csrf_token }}";
    </script>
    {% comment %}
    <link rel="shortcut icon" href="{{settings.favicon.img_value}}" />
    {% endcomment %} 
    {% block extra_header %} {% endblock %}
  </head>

  <body>
    {% include "./navbar.html" %} 
    
    {% block content %} 
    {% endblock content %} 


    {% if not hide_footer %}
      {% include "./footer.html" %}
    {% endif %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'splide/js/splide.min.js' %}"></script>
    <script src="{% static 'js/myjs.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% block extra_js %} {% endblock %}
  </body>
</html>

par/templates/frontend/footer.html
{% load static %}
<div
class="container-fluid p-0 d-flex justify-content-center align-items-center"
style="
  background-image: url('{%static "images/footer_banner.png" %}');
  background-repeat: no-repeat;
  background-size: cover;
  min-height: 240px;
"
> 
  <div class="container-md  d-none d-lg-block">
    <div class="row">
      <div class="col-lg-8 col-sm-12" style="padding-right: 8rem">
          <h2 class="text-white mb-3">{{ footer.ada_pertanyaan.val }}</h2>
          <p class="text-white text-12">
            {{ footer.ada_pertanyaan_desc.val |safe }}
          </p>
      </div>
      <div class="col-lg-4 col-sm-12">
        <p class="text-white mb-2 text-14"> Call Center </p>
        <a href="https://wa.me/88152900021" target="blank" >
          <img src="{%static 'images/call_center.png'%}" class="w-100" />
        </a>
      </div>
    </div>
  </div>

  <div class="container-md  d-lg-none py-5">
    <div class="row">
      <div class="col-lg-8 col-sm-12 text-center">
          <h2 class="text-white mb-3">{{ footer.ada_pertanyaan.val }}</h2>
          <p class="text-white text-12">
            {{ footer.ada_pertanyaan_desc.val |safe }}
          </p>
      </div>
      <div class="col-lg-4 col-sm-12 text-center mt-4">
        <p class="text-white mb-2 text-13"> Call Center </p>
        <a href="https://wa.me/88152900021" target="blank" _blank>
          <img src="{%static 'images/call_center.png'%}" class="w-50 mt-2" />
        </a>
      </div>
    </div>
  </div>
  
</div>

<div
  class="container-fluid p-sm-5"
  style="position: relative;"
>
  <div class="row w-100" style="width: 100%; margin: 0 !important">
    <div class="col-md-2 col-sm-6 d-flex flex-column footer-link mt-3">
      <h6 class="text-dark mb-2">{{ footer.bisnis_kami.val }}</h6>
      <a href="{% url 'frontend:our_business' %}#1">{{ footer.bisnis_kami_1.val }}</a>
      <a href="{% url 'frontend:our_business' %}#2">{{ footer.bisnis_kami_2.val }}</a>
      <a href="{% url 'frontend:our_business' %}#3">{{ footer.bisnis_kami_3.val }}</a>
    </div>
    <div class="col-md-2 col-sm-6 d-flex flex-column footer-link mt-3">
      <h6 class="text-dark mb-2">{{ footer.tentang_kami.val }}</h6>
      <a href="{% url 'frontend:aboutus' %}">{{ footer.profile_perusahaan.val }}</a>
      <a href="{% url 'frontend:management' %}">{{ footer.manajement.val }}</a>
      <a href="{% url 'frontend:aboutus' %}#award">{{ footer.penghargaan.val }}</a>
      <a href="{% url 'frontend:aboutus' %}#visimisi">Visi & Misi</a>
      <a href="{% url 'frontend:contactus' %}">{{ footer.kontak.val }}</a>
    </div>
    <div class="col-md-2 col-sm-6 d-flex flex-column footer-link mt-3">
      <h6 class="text-dark mb-2">{{ footer.quick_links.val }}</h6>
      <a href="{% url 'frontend:index' %}">{{ footer.beranda.val }}</a>
      <a href="{% url 'frontend:index' %}">{{ footer.patra_jasa.val }}</a>
    </div>
    <div class="col-md-2 col-sm-6 d-flex flex-column footer-link mt-3">
      <h6 class="text-dark mb-2">{{ footer.info.val }}</h6>
      <a href="{% url 'frontend:news' %}">{{ footer.news.val }}</a>
      <a href="{% url 'frontend:tjsl' %}">{{ common_settings.tjsl.val }}</a>
      <a href="{% url 'frontend:career' %}">{{ footer.karir.val }}</a>
      <a href="{% url 'frontend:tender' %}">{{ footer.tender.val }}</a>
      <a href="{% url 'frontend:gallery' %}">{{ footer.gallery.val }}</a>
    </div>
    <div class="col-md-4 col-sm-12 mt-3">
    <h6 class="text-dark">{{ footer.langganan_berita.val }}</h6>
    <form class="search-form" method="POST" id="redeemForm" name="search-form" action="">
      <div class="subscribe-form-input">
        <input type="email" name="email" class="email-input" placeholder="{{ footer.email_placeholder.val }}" required />
        <button type="submit" class="footer_btn_submit">
        <img class="footer_btn_submit_img" src="{%static 'images/btn_submit_email.png'%}"  />
        </button>
      </div>
    </form>
    <p class="mt-2" style="font-size: 0.8rem">
      {{ footer.subscribe_description.val |safe }}
    </p>
    <div class="d-flex mt-5 row-gap-5">
      <a class="me-3" href="{{common_settings.all_facebook_url.val}}" target="_blank"><img src="{% static 'images/facebook.png' %}" /></a>
      <a class="me-3" href="{{common_settings.all_linkedin_url.val}}" target="_blank"><img src="{% static 'images/linkedin.png' %}" /></a>
      <a class="me-3" href="{{common_settings.all_youtube_url.val}}" target="_blank"><img src="{% static 'images/youtube.png' %}" /></a>
      <a class="me-3" href="{{common_settings.all_instagram_url.val}}" target="_blank"><img src="{% static 'images/instagram.png' %}"/></a>
    </div>
    <img class="w-50 mt-5" src="{% static 'images/management.png' %}" />
    <div class="d-flex flex-row justify-content-between py-3 mt-4">
      <a href="" class="text-9">{{ footer.kebijakan_privasi.val }}</a>
      <a href="" class="text-9">© 2022 PT Prima Armada Raya</a>
    </div>
  </div>
</div>

<img
  style="position: absolute; width: 100px; bottom: 20%"
  src="{% static 'images/logo3.png' %}"
  class="d-none d-lg-block "
/>
</div>

{% block extra_js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
  <script>
    // SUBMIT REDEEM
  $("#redeemForm").submit(function (e) {
    console.log("sdfsdfsdfsdfsdfsd")
    e.preventDefault();
    var serializedData = $(this).serialize();
    console.log("serializedData", serializedData)
    $.ajax({
      type: 'POST',
      url: "{% url 'frontend:subscribe' %}",
      data: serializedData,
      success: function (response) {
        Swal.fire({
          title: 'Success!',
          text: 'Email anda berhasil didaftarkan',
          confirmButtonText: 'OK',
          confirmButtonColor: '#0C659D',        
        })
      },
      error: function (response) {
        Swal.fire({
          title: 'Error!',
          text: 'Mohon maaf terjadi kesalahan sistem kami, silahkan coba lagi',
          confirmButtonText: 'OK',
          confirmButtonColor: '#0C659D',   
        })
      }
    });
  });

</script>
{% endblock extra_js %}

par/templates/frontend/navbar.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% url 'frontend:index' as home_url %}
{% load templatehelpers %}

{% comment %} <nav class="navbar navbar-expand-md fixed-top navbar-white bg-white {% if request.get_full_path == home_url %} navbar-home {% endif %}" > {% endcomment %}
<nav class="navbar navbar-expand-md fixed-top navbar-white bg-white " >
  <div class="container-fluid ps-0 ">
    <div style="width: 15%">
      <a href = "/">
        <img src="{% static 'images/logo_home.png' %}" class="" alt="par-logo"  id="logoPAR" style="max-width: 80px; margin-left: 32px;"/>
      </a>
    </div>

    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarCollapse"
      aria-controls="navbarCollapse"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon">
        <i class="fa fa-navicon" style=" font-size:28px;"></i>
      </span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown1" role="button" data-bs-toggle="dropdown" aria-expanded="true">
            {{common_settings.tentang_kami.val}}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown1">
            <li><a class="dropdown-item" href="{% url 'frontend:aboutus'%}">{{common_settings.tentang_kami.val}}</a></li>
            <li><a class="dropdown-item" href="{% url 'frontend:management'%}">{{common_settings.profil_direksi.val}}</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'frontend:our_business'%}">{{common_settings.bisnis_kami.val}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'frontend:investor'%}">{{common_settings.hubungan_investor.val}}</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true">
            {{common_settings.media_informasi.val}}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><a class="dropdown-item" href="{% url 'frontend:news' %}">{{common_settings.artikel_dan_berita.val}}</a></li>
            <li><a class="dropdown-item" href="{% url 'frontend:gallery' %}">{{common_settings.gallery.val}}</a></li>
            <li><a class="dropdown-item" href="{% url 'frontend:tender' %}">{{common_settings.tender.val}}</a></li>
            <li><a class="dropdown-item" href="{% url 'frontend:career' %}">{{common_settings.karir.val}}</a></li>
            <li><a class="dropdown-item" href="{% url 'frontend:tjsl' %}">{{common_settings.tjsl.val}}</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'frontend:contactus'%}">{{common_settings.hubungi_kami.val}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'frontend:portal'%}">{{common_settings.portal.val}}</a>
      </ul>

      <form
        action="{% url 'frontend:search' %}"
        method="get"
        class="d-flex align-items-center border px-4 py-1 me-2 form-search"
        style="border-radius: 2rem;"
      >
        <i class="fa fa-search me-2"></i>
        <input
          name="query"
          class="searchinput"
          placeholder="Search"
          aria-label="Search"
          value= {%if query %}{{query}} {%else%} "" {%endif%}
          style="font-size: 1.1rem; border: none; background-color: transparent;"
        />
      </form>

      <div
        class="d-none d-md-flex border rounded-circle p-1 form-language"
        style="width: 2.2em"
      >
        {% if LANGUAGE_CODE == 'en' %}
          <span class="text-center w-100">
            <a href="{{ request.get_full_path|replace_lang}}" class="lang" lang="id">ID</a>
          </span> 
        {% else %}
          <span class="text-center w-100">
            <a href="{{ request.get_full_path|replace_lang}}" class="lang" lang="id">EN</a>
          </span> 
        {% endif %}
      </div>
    </div>
  </div>
</nav>